// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5jC0vYZB1ZyAYYnMPBahg5LIfgw8kp4',
    appId: '1:1034458039576:web:dc704ea456a70d42b18a6d',
    messagingSenderId: '1034458039576',
    projectId: 'animal-resource-allocator',
    authDomain: 'animal-resource-allocator.firebaseapp.com',
    storageBucket: 'animal-resource-allocator.appspot.com',
    measurementId: 'G-V098L9RN0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGUFEr04XwzMiGgZXgorKJ3SVTnMiGA0',
    appId: '1:1034458039576:android:aa3c71968835a48bb18a6d',
    messagingSenderId: '1034458039576',
    projectId: 'animal-resource-allocator',
    storageBucket: 'animal-resource-allocator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnMUpVdIdZEJALkOBJQNc7yQ-zMyaXNpw',
    appId: '1:1034458039576:ios:1c9f6f0726483e3fb18a6d',
    messagingSenderId: '1034458039576',
    projectId: 'animal-resource-allocator',
    storageBucket: 'animal-resource-allocator.appspot.com',
    iosClientId: '1034458039576-9488c4m5ma757f53amq7lsk0u73fjqlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalShelterResourceAllocator',
  );
}
